# Generated by Django 4.2.1 on 2023-05-24 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greatkartapp', '0003_product_db'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_db',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
