# Generated by Django 4.2.1 on 2023-05-25 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greatkartapp', '0004_alter_product_db_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_db',
            old_name='category_slug',
            new_name='slug',
        ),
    ]
