# Generated by Django 4.2.1 on 2023-05-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greatkartapp', '0006_cart_cat_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cat_item',
            new_name='cart_item',
        ),
    ]
