# Generated by Django 4.2.1 on 2023-05-29 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greatkartapp', '0012_alter_variation_variation_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='varaition_category',
            new_name='variation_category',
        ),
    ]
