# Generated by Django 4.2.1 on 2023-05-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greatkartapp', '0013_rename_varaition_category_variation_variation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='variations',
            field=models.ManyToManyField(blank=True, to='greatkartapp.variation'),
        ),
    ]
