# Generated by Django 4.2.1 on 2023-05-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greatkartapp', '0014_cart_item_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.IntegerField(max_length=50),
        ),
    ]
