# Generated by Django 4.2.1 on 2023-06-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greatkartapp', '0024_remove_orderproduct_color_remove_orderproduct_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='variation',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='variations',
            field=models.ManyToManyField(blank=True, to='greatkartapp.variation'),
        ),
    ]
