# Generated by Django 4.2.1 on 2023-06-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greatkartapp', '0025_remove_orderproduct_variation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.IntegerField(),
        ),
    ]
