# Generated by Django 4.2.1 on 2023-06-08 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greatkartapp', '0027_reviewrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewRating',
        ),
    ]
