# Generated by Django 4.2.1 on 2023-06-09 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greatkartapp', '0032_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
